# Generated by Django 5.2.5 on 2025-08-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='collected_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='capital',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='duree',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='fumeur',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='source',
            field=models.CharField(default='simulated', max_length=30),
        ),
    ]
